framework:
    cache:
        app: cache.adapter.array
        # Pour tester le cache tout en étant en dev
        # app: app.cache.adapter.redis
        prefix_seed: ekostreetstore.com
        default_redis_provider: '%env(resolve:REDIS_URL)%'
        pools:
            view_cache_pool:
                default_lifetime: '7 days'

services:
    app.cache.adapter.redis:
        parent: 'cache.adapter.redis'
        arguments:
            $defaultLifetime: 604800
        tags:
            - { name: 'cache.pool', namespace: 'eko_cache' }
